apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://dcim_prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: '15s'

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: https://10.70.0.56:9200
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: "ES_PASSWORD_REDACTED"
    database: "dcim-metrics-unified-*"
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      tlsSkipVerify: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: 10.70.0.56:5432
    database: dcim_sot
    user: sot_admin
    secureJsonData:
      password: ${SOT_DB_PASS}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
