[[inputs.redfish]]
  address = "https://10.50.0.2"
  username = "hndept"
  password = "F!tech@0918"
  insecure_skip_verify = true
  interval = "60s"
  name_override = "server_redfish"
  [inputs.redfish.tags]
    host = "server-HCI-01"

[[inputs.redfish]]
  address = "https://10.50.0.3"
  username = "hndept"
  password = "F!tech@0918"
  insecure_skip_verify = true
  interval = "60s"
  name_override = "server_redfish"
  [inputs.redfish.tags]
    host = "server-HCI-02"

[[inputs.redfish]]
  address = "https://10.50.0.4"
  username = "hndept"
  password = "F!tech@0918"
  insecure_skip_verify = true
  interval = "60s"
  name_override = "server_redfish"
  [inputs.redfish.tags]
    host = "server-HCI-03"

[[inputs.redfish]]
  address = "https://10.50.0.5"
  username = "hndept"
  password = "F!tech@0918"
  insecure_skip_verify = true
  interval = "60s"
  name_override = "server_redfish"
  [inputs.redfish.tags]
    host = "server-Render-01"

[[inputs.redfish]]
  address = "https://10.50.0.6"
  username = "root"
  password = "F!tech@0918"
  insecure_skip_verify = true
  interval = "60s"
  name_override = "server_redfish"
  [inputs.redfish.tags]
    host = "server-Render-02"
