[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  hostname = "srv-rnd-dcim-consumer"

[[inputs.kafka_consumer]]
  brokers = ["127.0.0.1:9092"]
  topics = ["dcim.enriched.events"]
  consumer_group = "telegraf_unified_consumer_v3"
  offset = "oldest"
  data_format = "json_v2"
  [[inputs.kafka_consumer.json_v2]]
      measurement_name_path = "name"
      timestamp_path = "timestamp"
      timestamp_format = "unix"
      [[inputs.kafka_consumer.json_v2.object]]
          path = "tags"
          tags = ["*"]
          disable_prepend_keys = true
      [[inputs.kafka_consumer.json_v2.object]]
          path = "fields"
          disable_prepend_keys = true

# --- UNIFIED ELASTICSEARCH OUTPUT ---
[[outputs.elasticsearch]]
  urls = ["https://10.70.0.56:9200"]
  insecure_skip_verify = true
  username = "elastic"
  password = "C+H+pFb*aIAqWcOo-X8q"
  index_name = "dcim-metrics-unified-%Y.%m.%d"
  manage_template = true
  template_name = "dcim-metrics-unified"
  overwrite_template = false
