[[inputs.snmp]]
  agents = ["192.168.100.140:161"]
  version = 3
  sec_name = "hndept"
  sec_level = "authPriv"
  auth_protocol = "SHA"
  auth_password = "F!tech0918"
  priv_protocol = "AES"
  priv_password = "F!tech0918"
  interval = "60s"
  name = "ups_apc"

  [[inputs.snmp.field]]
    name = "system_name"
    oid = ".1.3.6.1.2.1.1.5.0"

  [[inputs.snmp.field]]
    name = "system_location"
    oid = ".1.3.6.1.2.1.1.6.0"

  [[inputs.snmp.field]]
    name = "system_description"
    oid = ".1.3.6.1.2.1.1.1.0"

  [[inputs.snmp.field]]
    name = "model"
    oid = ".1.3.6.1.4.1.935.1.1.1.1.1.1.0"
  
  [[inputs.snmp.field]]
    name = "status"
    oid = ".1.3.6.1.4.1.935.1.1.1.4.1.1.0"

  [[inputs.snmp.field]]
    name = "battery_capacity"
    oid = ".1.3.6.1.4.1.935.1.1.1.2.2.1.0"

  [[inputs.snmp.field]]
    name = "battery_runtime_remain"
    oid = ".1.3.6.1.4.1.935.1.1.1.2.2.3.0"

  [[inputs.snmp.field]]
    name = "battery_temp"
    oid = ".1.3.6.1.4.1.935.1.1.1.2.2.2.0"

  [[inputs.snmp.field]]
    name = "input_voltage"
    oid = ".1.3.6.1.4.1.935.1.1.1.3.2.1.0"

  [[inputs.snmp.field]]
    name = "output_voltage"
    oid = ".1.3.6.1.4.1.935.1.1.1.4.2.1.0"

  [[inputs.snmp.field]]
    name = "output_load"
    oid = ".1.3.6.1.4.1.935.1.1.1.4.2.3.0"

  [[inputs.snmp.field]]
    name = "serial_number"
    oid = ".1.3.6.1.2.1.33.1.1.1.0"

  [[inputs.snmp.field]]
    name = "firmware_version"
    oid = ".1.3.6.1.2.1.33.1.1.3.0"

  [[inputs.snmp.field]]
    name = "agent_firmware"
    oid = ".1.3.6.1.2.1.33.1.1.4.0"

  [[inputs.snmp.field]]
    name = "battery_status"
    oid = ".1.3.6.1.2.1.33.1.2.1.0"

  [[inputs.snmp.field]]
    name = "battery_seconds_on_battery"
    oid = ".1.3.6.1.2.1.33.1.2.2.0"

  [[inputs.snmp.field]]
    name = "battery_voltage"
    oid = ".1.3.6.1.2.1.33.1.2.5.0"

  [[inputs.snmp.field]]
    name = "battery_current"
    oid = ".1.3.6.1.2.1.33.1.2.6.0"

  [[inputs.snmp.field]]
    name = "input_frequency_L1"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.2.1"
  [[inputs.snmp.field]]
    name = "input_frequency_L2"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.2.2"
  [[inputs.snmp.field]]
    name = "input_frequency_L3"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.2.3"
  [[inputs.snmp.field]]
    name = "input_voltage_L1"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.3.1"
  [[inputs.snmp.field]]
    name = "input_voltage_L2"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.3.2"
  [[inputs.snmp.field]]
    name = "input_voltage_L3"
    oid = ".1.3.6.1.2.1.33.1.3.3.1.3.3"
  [[inputs.snmp.field]]
    name = "output_frequency"
    oid = ".1.3.6.1.2.1.33.1.4.2.0"
  [[inputs.snmp.field]]
    name = "output_voltage_L1"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.2.1"
  [[inputs.snmp.field]]
    name = "output_voltage_L2"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.2.2"
  [[inputs.snmp.field]]
    name = "output_voltage_L3"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.2.3"
  [[inputs.snmp.field]]
    name = "output_current_L1"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.3.1"
  [[inputs.snmp.field]]
    name = "output_current_L2"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.3.2"
  [[inputs.snmp.field]]
    name = "output_current_L3"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.3.3"
  [[inputs.snmp.field]]
    name = "output_load_L1"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.5.1"
  [[inputs.snmp.field]]
    name = "output_load_L2"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.5.2"
  [[inputs.snmp.field]]
    name = "output_load_L3"
    oid = ".1.3.6.1.2.1.33.1.4.4.1.5.3"

  [inputs.snmp.tags]
    device_type = "ups"
    location = "Server Room"
