[[inputs.http]]
  urls = [
    "https://10.50.0.5/redfish/v1/Systems/1",
    "https://10.50.0.5/redfish/v1/Chassis/1",
    "https://10.50.0.5/redfish/v1/Managers/1"
  ]
  username = "hndept"
  password = 'F!tech@0918'
  insecure_skip_verify = true
  timeout = "15s"
  data_format = "json"
  name_override = "server_inventory"
  json_string_fields = ["Model", "Oem_Lenovo_ProductName", "SerialNumber", "BiosVersion", "FirmwareVersion", "PowerState", "HostName", "Status_Health"]

  [inputs.http.tags]
    address = "10.50.0.5"
    device_type = "server"

[[processors.converter]]
  namepass = ["server_inventory"]
  [processors.converter.tags]
    string = ["url"]

[[aggregators.merge]]
  drop_original = true
